name: Update Epsiloon Cover

on:
  schedule:
    # Tous les jours à 08:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch:  # permet de lancer manuellement

jobs:
  update-cover:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Scrape Cover
      run: python scrape.py

    - name: Commit and Push Cover
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # Crée un secret PAT dans ton repo
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add cover.jpg
        git commit -m "Mise à jour couverture" || echo "Aucune modification"
        git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
        git push origin HEAD:main
