name: Update Cover

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-cover:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important pour pouvoir pousser

      - name: Installer Python (si besoin)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Générer cover.jpg
        run: |
          # Remplace cette partie par ton script de génération
          echo "Hello Cover" > cover.jpg

      - name: Configurer Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit et Push si modification
        run: |
          if [ -f "cover.jpg" ]; then
            git add cover.jpg
            if git diff --cached --quiet; then
              echo "Aucune modification à commit."
            else
              git commit -m "Mise à jour couverture"
              git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/NotXaze/Epsiloon-Cover.git
              git push origin HEAD:main
            fi
          else
            echo "cover.jpg n'existe pas, rien à pousser."
          fi
