name: Update Cover

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # Tous les jours à 8h UTC

jobs:
  update-cover:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # 3️⃣ Exécuter scrape.py pour générer cover.jpg
      - name: Run scrape.py
        run: python scrape.py

      # 4️⃣ Commit et push avec PAT
      - name: Commit and Push cover.jpg
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          if [ -f "cover.jpg" ]; then
            echo "cover.jpg trouvé ✅"
            git add cover.jpg
            if git diff --cached --quiet; then
              echo "Aucune modification à commit."
            else
              git commit -m "Mise à jour couverture"
              git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/NotXaze/Epsiloon-Cover.git
              git push origin HEAD:main
            fi
          else
            echo "cover.jpg n'existe pas ❌"
          fi
