name: Update Cover

on:
  schedule:
    - cron: "0 8 * * *" # tous les jours à 8h
  workflow_dispatch: # permet de lancer manuellement

jobs:
  update-cover:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python scrape.py

      - name: Commit and push cover.jpg if changed
        uses: peter-evans/commit-and-push-action@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Mise à jour couverture"
          file-pattern: cover.jpg
