name: Update Cover

on:
  schedule:
    - cron: '0 8 * * *' # tous les jours à 8h
  workflow_dispatch:

jobs:
  update-cover:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python scrape.py

      - name: Commit and push cover.jpg if changed
        run: |
          if [ -f "cover.jpg" ]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add cover.jpg
            if ! git diff --cached --quiet; then
              git commit -m "Mise à jour couverture"
              git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/NotXaze/Epsiloon-Cover.git HEAD:main
            else
              echo "Aucune modification à commit."
            fi
          else
            echo "cover.jpg n'existe pas, rien à pousser."
          fi
